"""
Base repository pattern.

Repositories are the ONLY way to talk to the database.
Services never write SQL. They call repository methods.
This makes testing trivial (swap DB for in-memory dict) and
keeps all SQL in one predictable place.

Karpathy rule: every method is explicit. No magic query builders.
The SQL should be readable by a human, not generated by 5 layers of ORM magic.
"""
from __future__ import annotations

import uuid
from typing import Generic, TypeVar

from sqlalchemy.ext.asyncio import AsyncSession

ModelT = TypeVar("ModelT")


class BaseRepository(Generic[ModelT]):
    """
    Generic base. Subclasses define their model type.

    Usage:
        class ListingRepository(BaseRepository[Listing]):
            model_class = Listing
            ...
    """
    model_class: type[ModelT]

    def __init__(self, session: AsyncSession) -> None:
        # The session is injected — the repository never creates its own session.
        # This enables transactional consistency: multiple repos in one request
        # share the same session and commit/rollback together.
        self.session = session

    async def get_by_id(self, entity_id: uuid.UUID) -> ModelT | None:
        raise NotImplementedError(
            f"{self.__class__.__name__}.get_by_id() must be implemented"
        )

    async def save(self, entity: ModelT) -> ModelT:
        raise NotImplementedError(
            f"{self.__class__.__name__}.save() must be implemented"
        )

    async def delete(self, entity_id: uuid.UUID) -> bool:
        raise NotImplementedError(
            f"{self.__class__.__name__}.delete() must be implemented"
        )
