#!/usr/bin/env python3
"""Splice the shared nav menu + footer into every static page.

The canonical markup lives here. Pages carry marker comments:

    <!-- SITE:MENU START --> ... <!-- SITE:MENU END -->      (nav dropdowns)
    <!-- SITE:FOOTER START --> ... <!-- SITE:FOOTER END -->  (whole footer)

Run `python3 tools/build_shared.py` after editing MENU_HTML/FOOTER_HTML to
push the change to all pages. Idempotent. Pages without markers are migrated
from the legacy (pre-marker) markup on first run.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

STATIC = Path(__file__).resolve().parent.parent / "src" / "defrosted" / "static"

MENU_HTML = """<!-- SITE:MENU START (generated by tools/build_shared.py — edit there) -->
      <div class="nav-item">
        <button class="nav-link">Product <span class="caret">▼</span></button>
        <div class="nav-dropdown">
          <a href="/how-it-works">How it works</a>
          <a href="/pricing">Pricing</a>
          <a href="/laws">State laws</a>
          <a href="/help">Help &amp; FAQ</a>
        </div>
      </div>
      <div class="nav-item">
        <button class="nav-link">Company <span class="caret">▼</span></button>
        <div class="nav-dropdown">
          <a href="/company">About us</a>
          <a href="/team">Team</a>
          <a href="/careers">Careers</a>
          <a href="/blog">Blog</a>
          <a href="/contact">Contact</a>
        </div>
      </div>
      <!-- SITE:MENU END -->"""

FOOTER_HTML = """<!-- SITE:FOOTER START (generated by tools/build_shared.py — edit there) -->
<footer>
  <div class="ft-top">
    <div class="ft-brand">
      <a class="logo" href="/">Defrost<span>.AI</span></a>
      <p>The AI agent that works for the renter, not the landlord. Starting in California.</p>
    </div>
    <div class="ft-cols">
      <div class="ft-col">
        <div class="ft-col-title">Product</div>
        <a href="/how-it-works">How it works</a>
        <a href="/pricing">Pricing</a>
        <a href="/laws">State laws</a>
        <a href="/legal/security">Security &amp; trust</a>
      </div>
      <div class="ft-col">
        <div class="ft-col-title">Company</div>
        <a href="/company">About us</a>
        <a href="/team">Team</a>
        <a href="/careers">Careers</a>
        <a href="/blog">Blog</a>
        <a href="/contact">Contact</a>
      </div>
      <div class="ft-col">
        <div class="ft-col-title">Resources</div>
        <a href="/help">Help &amp; FAQ</a>
        <a href="/blog">Renter guides</a>
        <a href="/laws">Laws by state</a>
        <a href="/contact#press">Press</a>
      </div>
      <div class="ft-col">
        <div class="ft-col-title">Legal</div>
        <a href="/legal/terms">Terms of Service</a>
        <a href="/legal/privacy">Privacy Policy</a>
        <a href="/legal/cookies">Cookie Policy</a>
        <a href="/legal/accessibility">Accessibility</a>
        <a href="/legal/fair-housing">Fair Housing</a>
        <a href="/legal/privacy#ccpa">Do Not Sell or Share My Personal Information</a>
      </div>
    </div>
  </div>
  <!-- All legal/compliance copy in this block is placeholder pending attorney review. Do not treat as final. -->
  <div class="ft-compliance">
    <!-- source: AI-agent transparency — consumer-protection best practice; CA B&P 17941 (SB 1001) bot disclosure. [[LEGAL REVIEW REQUIRED: final wording]] -->
    <p>Defrost.AI is an AI-powered service. Any outreach it performs on your behalf is written-only, sent solely with your explicit authorization, and identifies itself as an AI agent acting for you.</p>
    <!-- source: CA DRE licensing / PRLS considerations (B&P 10131(b), 10167) — see docs/WEBSITE_SPEC.md. [[LEGAL REVIEW REQUIRED: licensing disclosure; do not publish a license number until one exists]] -->
    <p>Defrost.AI is not a licensed real estate broker and does not negotiate rentals for compensation.</p>
  </div>
  <div class="ft-bottom">
    <div class="ft-bottom-inner">
      <div class="ft-legal-line">
        <!-- [[PLACEHOLDER: confirm exact legal entity name + add mailing address here]] -->
        <span>© 2026 Defrost.AI — All rights reserved.</span>
        <span class="eho" title="Equal Housing Opportunity">
          <!-- Placeholder mark: replace with the official HUD Equal Housing Opportunity logo asset. [[LEGAL REVIEW: confirm EHO logo usage + wording]] -->
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 1.5 1 10h3v12.5h16V10h3L12 1.5zM18 20.5H6V9.3l6-4.6 6 4.6V20.5zM8 12h8v2.2H8V12zm0 4h8v2.2H8V16z"/></svg>
          Equal Housing Opportunity
        </span>
      </div>
      <div class="ft-social">
        <!-- Only real accounts are linked. Add others when they exist. -->
        <a href="https://www.linkedin.com/company/defrostedai" target="_blank" rel="noopener" aria-label="Defrost.AI on LinkedIn"><svg viewBox="0 0 24 24"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg></a>
      </div>
    </div>
  </div>
</footer>
<!-- SITE:FOOTER END -->"""

MENU_RE = re.compile(r"<!-- SITE:MENU START.*?<!-- SITE:MENU END -->", re.S)
FOOTER_RE = re.compile(r"<!-- SITE:FOOTER START.*?<!-- SITE:FOOTER END -->", re.S)

# One-time migration patterns for legacy pages (pre-marker markup).
LEGACY_MENU_RE = re.compile(
    r'<div class="nav-item">\s*<button class="nav-link">Company.*?</div>\s*</div>\s*'
    r'<div class="nav-item">\s*<button class="nav-link">Resources.*?</div>\s*</div>',
    re.S,
)
LEGACY_FOOTER_RE = re.compile(r"<footer>.*?</footer>", re.S)


def process(path: Path) -> None:
    html = path.read_text(encoding="utf-8")
    orig = html

    if MENU_RE.search(html):
        html = MENU_RE.sub(lambda _: MENU_HTML, html)
    elif LEGACY_MENU_RE.search(html):
        html = LEGACY_MENU_RE.sub(lambda _: MENU_HTML, html, count=1)
    else:
        print(f"  {path.name}: no nav menu found (skipped menu)")

    if FOOTER_RE.search(html):
        html = FOOTER_RE.sub(lambda _: FOOTER_HTML, html)
    elif LEGACY_FOOTER_RE.search(html):
        html = LEGACY_FOOTER_RE.sub(lambda _: FOOTER_HTML, html, count=1)
    else:
        print(f"  {path.name}: no footer found (skipped footer)")

    if html != orig:
        path.write_text(html, encoding="utf-8")
        print(f"  {path.name}: updated")
    else:
        print(f"  {path.name}: unchanged")


def main() -> int:
    pages = sorted(
        p
        for p in STATIC.rglob("*.html")
        if p.name != "rent_vs_buy.html"  # the app, not the marketing site
    )
    for p in pages:
        process(p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
